name: John Harding JD
favicon: null
layout_spectrum: 0.49648
typography_spectrum: 0.64115
title: 'John Harding, California Family Law Lawyer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#015601'
    - '#000000'
    - '#8eb48f'
    - '#5f5f5f'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
